### ISSUE TITLE
Positive Feedback

### ISSUE THREAD

**Issue by ImperiumKontratakuje** [DataBot-Labs/hoverboard_ros2_control#7]
I would like to sincerely thank the team, Bart Van der Haagen and Robert Gruberski
for their work and for providing the driver for ROS2.
I have tested almost all the projects related to this topic available on GitHub, and with the driver from this repository, I am achieving the best results :)

https://youtu.be/By6ZZIxmBJ8

Great job!
Thank you very much.

![ant2](https://github.com/user-attachments/assets/527db05a-318e-4996-b623-8b348030861b)

**Comment by rgruberski** [comment]
@ImperiumKontratakuje It fills my heart to see that our project is valuable and used in the actual project! Thank you! I am going to share it on LinkedIn. :) Please let us know if you need any help with the project. By the way, I am going to close this issue to keep the project clean.

**Comment by sebastienvg** [comment]
> I would like to sincerely thank the team, Bart Van der Haagen and Robert Gruberski for their work and for providing the driver for ROS2. I have tested almost all the projects related to this topic available on GitHub, and with the driver from this repository, I am achieving the best results :)
> 
> https://youtu.be/By6ZZIxmBJ8
> 
> Great job! Thank you very much.
> 
> ![ant2](https://private-user-images.githubusercontent.com/85103771/364157149-527db05a-318e-4996-b623-8b348030861b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MzY5MTUsIm5iZiI6MTczNDYzNjYxNSwicGF0aCI6Ii84NTEwMzc3MS8zNjQxNTcxNDktNTI3ZGIwNWEtMzE4ZS00OTk2LWI2MjMtOGIzNDgwMzA4NjFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE5MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MDg1NzFiZDkzOGI1NGU2Yzg3ZGQ2M2NlMzJhZjU3ZmEyZmZmYmE5NDhhNmRkMTAwZjczMzhlNTQ1YmM5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uTICQGZxm3noPNowGYsvAAS0J6g-sqN2YF6jxTlO98M)

I am toying around with ROS and the hoverboard for a couple weeks now and I want to move on with ROS2, do you have a github repo where you share the detail of your project?

**Comment by rgruberski** [comment]
> > I would like to sincerely thank the team, Bart Van der Haagen and Robert Gruberski for their work and for providing the driver for ROS2. I have tested almost all the projects related to this topic available on GitHub, and with the driver from this repository, I am achieving the best results :)
> > https://youtu.be/By6ZZIxmBJ8
> > Great job! Thank you very much.
> > ![ant2](https://private-user-images.githubusercontent.com/85103771/364157149-527db05a-318e-4996-b623-8b348030861b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MzY5MTUsIm5iZiI6MTczNDYzNjYxNSwicGF0aCI6Ii84NTEwMzc3MS8zNjQxNTcxNDktNTI3ZGIwNWEtMzE4ZS00OTk2LWI2MjMtOGIzNDgwMzA4NjFiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDE5MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MDg1NzFiZDkzOGI1NGU2Yzg3ZGQ2M2NlMzJhZjU3ZmEyZmZmYmE5NDhhNmRkMTAwZjczMzhlNTQ1YmM5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uTICQGZxm3noPNowGYsvAAS0J6g-sqN2YF6jxTlO98M)
> 
> I am toying around with ROS and the hoverboard for a couple weeks now and I want to move on with ROS2, do you have a github repo where you share the detail of your project?

Hi @sebastienvg! I don't know what @ImperiumKontratakuje  can share and what is available publicly. But in the project repository, you have a complete example available (urdf, config, bring up). What do you need? Maybe we will be able to help :)
